### ISSUE TITLE
this is what i wanted!!

### ISSUE THREAD

**Issue by kency** [AdrienPoupa/laradate#1]
but could you make a composer package to install with 'composer require',really need it.
very tks LA~

**Comment by AdrienPoupa** [comment]
Thank you. Very good idea!

**Comment by AdrienPoupa** [comment]
It is done now: https://packagist.org/packages/adrienpoupa/laradate

I will publish the 1.0 when I feel it is stable. In the meantime, you can just use "dev-master".
